### ISSUE TITLE
Azure Gov

### ISSUE THREAD

**Issue by cheapshot2000** [hteo1337/UiPathOrchestrator#2]
Any way we can get this working for Azure Government regions?  They have different site regions, different supported API's and also they do NOT support Application insights.

I was able to get the deployment to go to an Azure gov region.  However, the app still won't load due to it wanting to leverage Application Insights.  

In the variables section, i modified to include a US Gov region:

        "logAnalyticsLocationMap": {
            "US Gov Virginia": "usgovvirginia",
            "usgovvirginia": "usgovvirginia",
            "eastasia": "southeastasia",

In the App Service Plan (aka serverFarms) i changed the apiVersion:

        {
            "apiVersion": "2018-02-01",
            "name": "[variables('appServicePlanName')]",
            "type": "Microsoft.Web/serverFarms",
            "location": "[parameters('location')]",
            "kind": "",

[RPA Orch Azure Gov Deployment Template - Copy.txt](https://github.com/hteo1337/UiPathOrchestrator/files/3131479/RPA.Orch.Azure.Gov.Deployment.Template.-.Copy.txt)

**Comment by hteo1337** [comment]
Hi, yes we will do it for Azure Gov also.

**Comment by hteo1337** [comment]
Hi. The new template should solve the problem. Now you can deploy the template with AppInsight and AppInsight rules.
